### ISSUE TITLE
Building on Ubuntu fails

### ISSUE THREAD

**Issue by PanderMusubi** [Bitcoin-sCrypt/Bitcoin-sCrypt#4]
Building 7382d42dc5d9ae17cecd43fbd37eb89b2ebb439c on Ubuntu fails. `make` results in

    ...
    src/net.cpp:53:1: error: reference to ‘array’ is ambiguous
     array<int, THREAD_MAX> vnThreadsRunning;
     ^~~~~
    In file included from src/net.h:11:0,
                     from src/main.h:11,
                     from src/db.h:10,
                     from src/net.cpp:9:
    /usr/include/boost/array.hpp:60:11: note: candidates are: template<class T, long unsigned int N> class boost::array
         class array {
               ^~~~~
    In file included from /usr/include/c++/7/tuple:39:0,
                     from /usr/include/c++/7/bits/stl_map.h:63,
                     from /usr/include/c++/7/map:61,
                     from src/util.h:13,
                     from src/bignum.h:14,
                     from src/main.h:10,
                     from src/db.h:10,
                     from src/net.cpp:9:
    /usr/include/c++/7/array:94:12: note:                 template<class _Tp, long unsigned int _Nm> struct std::array
         struct array
                ^~~~~
    Makefile:1273: recipe for target 'build/net.o' failed
    make: *** [build/net.o] Error 1

Packages installed were:

    apt-get install qt4-qmake libqt4-dev build-essential libboost-dev libboost-system-dev libboost-filesystem-dev libboost-program-options-dev libboost-thread-dev libssl-dev libdb5.3++-dev

Also dozens of warnings `invalid suffix on literal; C++11 requires a space between literal and string macro` were reported during build. Please, fix those too.

In order to mitigate the Berkely DB version issue, please offer releases here on GitHub for latest stable Debian and Ubuntu and Ubuntu LTS.

**Comment by Spidersbox** [comment]
BerkeleyDB is required for the wallet. db4.8 packages are available here. You can add the repository and install using the following commands:

sudo add-apt-repository ppa:bitcoin/bitcoin
sudo apt-get update
sudo apt-get install libdb4.8-dev libdb4.8++-dev


and for older boost:
to install boost:
mkdir ~/boost_build && cd ~/boost_build && \
wget http://sourceforge.net/projects/boost/files/boost/1.48.0/boost_1_48_0.tar.gz && \
tar xvf boost_1_48_0.tar.gz && cd boost_1_48_0 && \
sed -i_bak -e 's#PREFIX=/usr/local#PREFIX=/opt#' -e 's#LIBDIR=#LIBDIR=/opt/boost/lib#' \
-e 's#INCLUDEDIR=#INCLUDEDIR=/opt/boost/include#' bootstrap.sh && \
./bootstrap.sh && ./b2 && \
sudo ./bjam install

./bootstrap.sh --prefix=/usr/local
sudo ./b2 install

**Comment by PanderMusubi** [comment]
Thanks. Perhaps add this also to the documentation.

The part with libdb works for me. Building boost works too, but I stopped at the installation. For my normal work, I am using boost and I do not want these versions to interfere on my machines. Could you add a statically linked build to the release here in GitHub please? I think many other less tech savvy Linux users would be happy with that too.

**Comment by Spidersbox** [comment]
net.cpp is now updated and should work with new boost - give it a try.

**Comment by Jay-Smoke** [comment]
Thanks Spidersbox
